#!/bin/sh
for i
do
	d=`dirname $i`
	f=`basename $i .java`
	echo $d/$f:
	java parser/TestParser $d/$f.java 1> $d/$f.ast 2>$d/$f.perr
	if [ -r $d/$f.ast.ref ]; then diff -w $d/$f.ast $d/$f.ast.ref; fi
	if [ -r $d/$f.perr.ref ]; then diff -w $d/$f.perr $d/$f.perr.ref; 
	else cat $d/$f.perr; fi
done
exit 0

